# Generated by Django 4.1.2 on 2022-10-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_class',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
