# Generated by Django 4.1.2 on 2022-10-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_user_school_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
