# Generated by Django 4.1.2 on 2022-10-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_mark'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('first_name__gte', 'A'), ('first_name__lte', 'Z')), name='first_name_uppercase'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('last_name__gte', 'A'), ('last_name__lte', 'Z')), name='last_name_uppercase'),
        ),
    ]
